feat: add support to multitenancy
juspay/hyperswitch-encryption-service pull request #37
Opened 2024-12-31 12:05 UTC by dracarys18

2025-01-02 03:03 UTC, jarnura submitted a review, later dismissed

2025-01-02 03:03 UTC, jarnura commented on config/development.toml
> +schema = "public"
use the schema of global instead configuring as public

2025-01-02 07:58 UTC, jarnura submitted a review, later dismissed

2025-01-02 13:41 UTC, dracarys18 commented on config/development.toml
> +schema = "public"
Done

2025-01-03 11:21 UTC, SanchithHegde approved these changes

2025-01-03 14:41 UTC, apoorvdixit88 approved these changes

2025-01-06 07:34 UTC, jagan-jaya requested changes

2025-01-06 07:34 UTC, jagan-jaya commented on config/development.toml
> +schema = "global"
why are we using global schema by default? do we need both schema by default? This is from an opensource perspective.

2025-01-06 07:34 UTC, jagan-jaya commented on benches/encryption_bench.rs
> +        .get(&TenantId::new("public".to_string()))
move this to a const

2025-01-06 07:34 UTC, jagan-jaya commented on benches/encryption_bench.rs
> +        .get(&TenantId::new("public".to_string()))
move this to a const

2025-01-06 07:34 UTC, jagan-jaya commented on src/consts.rs
> +pub const TENANANT_HEADER: &str = "x-tenant-id";
correct this typo

2025-01-06 07:34 UTC, jagan-jaya commented on src/env/logger.rs
> +                tracing::event!(tracing::Level::INFO, "Started processing request");
why is the log message same for all the levels? is it expected?

2025-01-06 07:34 UTC, jagan-jaya commented on src/env/logger.rs
> +                    "Finished processing request"
is it expected to have same error message for all levels

2025-01-06 07:34 UTC, jagan-jaya commented on src/errors/app.rs
> +    TenantIDNotFound,
```suggestion
    TenantIdNotFound,
```

2025-01-06 07:34 UTC, jagan-jaya commented on src/multitenancy.rs
> +            .get("x-tenant-id")
use const

2025-01-06 07:35 UTC, jagan-jaya commented on config/development.toml
> +schema = "global"
In psql "public" schema is created automatically by postgres during first time. No other schema will be present

2025-01-06 07:56 UTC, dracarys18 commented on config/development.toml
> +schema = "global"
This is not default tenant, I am just configuring schema as `global` for global tenant. Whenever router sends `x-tenant-id` as `global` it will access schema and cache prefix from here

2025-01-06 07:57 UTC, dracarys18 commented on src/env/logger.rs
> +                tracing::event!(tracing::Level::INFO, "Started processing request");
Yes, This is a message to be printed when the request starts. No matter what the log level you provide message should be the same

2025-01-06 07:57 UTC, dracarys18 commented on src/env/logger.rs
> +                    "Finished processing request"
Yes

2025-01-06 09:14 UTC, jagan-jaya approved these changes

2025-01-06 09:43 UTC, SanchithHegde approved these changes

2025-01-06 11:57 UTC, apoorvdixit88 approved these changes

2025-01-06 12:18 UTC, merged